# Generated by Django 4.0.1 on 2022-01-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusSatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusNo', models.CharField(max_length=10)),
                ('BusContactNo', models.CharField(max_length=10)),
                ('DriverName', models.CharField(max_length=50)),
                ('ConductorName', models.CharField(max_length=50)),
                ('DepartureTime', models.CharField(max_length=50)),
                ('ArrivalTime', models.CharField(max_length=50)),
                ('LastService', models.CharField(max_length=50)),
                ('PUC', models.DateTimeField()),
                ('Insurance', models.DateTimeField()),
                ('DriverContactNo', models.CharField(max_length=50)),
                ('ConductorContactNo', models.CharField(max_length=50)),
            ],
        ),
    ]
